version: '3'
services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: plex-stats
    restart: unless-stopped
    volumes:
      - /Docker/plex-stats/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 8181:8181
