services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Docker/radarr/config:/config
      - /nas/Films:/nas/Films #optional
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Docker/sonarr/config:/config
      - /nas/TV/TV:/nas/TV #optional
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent-Films:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-Films
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /Docker/qbittorrent/config:/config
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
 
  qbittorrent-TV:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-TV
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8081
      - TORRENTING_PORT=6882
    volumes:
      - /Docker/qbittorrent-tv/config:/config
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 8081:8081
      - 6882:6882
      - 6882:6882/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/London
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /Docker/overseerr/config:/app/config
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /Docker/bazarr/config:/config
      - /nas/Films/Films:/nas/Films/Films #optional
      - /nas/TV/TV:/nas/TV/TV #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=iPZmz17iqfP7LmgdSh9UXlyTlgsMfuEjGqfdUAzZvl0=
      - WIREGUARD_ADDRESSES=100.101.143.197/32
      - WIREGUARD_PRESHARED_KEY=0H3hYoyyihhq+OdC7BgJWd0RJB7Qn00C66U7GpF98jw=
      - SERVER_REGIONS=united kingdom
    restart: unless-stopped
