services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-SLo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Docker/radarr-SLo/config:/config
      - /nas/Films:/nas/Films #optional
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 7880:7878
    restart: unless-stopped

  bittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent-SLo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8083
      - TORRENTING_PORT=6884
    volumes:
      - /Docker/qbittorrent-SLo/config:/config
      - /nas/Torrents:/nas/Torrents #optional
    ports:
      - 8083:8083
      - 6884:6884
      - 6884:6884/udp
    restart: unless-stopped
